version: '3.8'

services:
  web:
    build:
      context: .
    container_name: apache_web
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
